-- Run this in Supabase Dashboard → SQL Editor
-- Adds tags column if missing, then upserts all 25 founders

alter table founders add column if not exists tags text[] default '{}';

insert into founders (slug, name, initials, title, company, quote, tags) values
  ('jeff-bezos',        'Jeff Bezos',          'JB',  'Founder & Executive Chairman, Amazon',    'Amazon',                'Day 2 is stasis. Followed by irrelevance. Followed by excruciating, painful decline. Followed by death.',                                                          array['customer-obsession','long-term','decision-making']),
  ('alex-hormozi',      'Alex Hormozi',         'AH',  'Founder, Acquisition.com',                'Acquisition.com',       'You must do so much volume that it would be unreasonable to suck.',                                                                                             array['sales','offers','volume']),
  ('sam-altman',        'Sam Altman',           'SA',  'CEO, OpenAI',                             'OpenAI',                'The most successful people I know believe in themselves almost to the point of delusion.',                                                                       array['startups','ai','compounding']),
  ('paul-graham',       'Paul Graham',          'PG',  'Co-founder, Y Combinator',                'Y Combinator',          'A startup is a company designed to grow fast.',                                                                                                                  array['startups','growth','essays']),
  ('naval-ravikant',    'Naval Ravikant',        'NR',  'Co-founder, AngelList',                   'AngelList',             'Specific knowledge is knowledge that you cannot be trained for. If society can train you, it can train someone else, and replace you.',                          array['wealth','leverage','philosophy']),
  ('elon-musk',         'Elon Musk',            'EM',  'CEO, Tesla & SpaceX',                     'Tesla / SpaceX',        'When something is important enough, you do it even if the odds are not in your favor.',                                                                          array['vision','engineering','risk']),
  ('reid-hoffman',      'Reid Hoffman',         'RH',  'Co-founder, LinkedIn',                    'LinkedIn',              'If you are not embarrassed by the first version of your product, you''ve launched too late.',                                                                    array['networking','scaling','vc']),
  ('peter-thiel',       'Peter Thiel',          'PT',  'Co-founder, PayPal & Palantir',           'PayPal / Palantir',     'Competition is for losers. If you want to create and capture lasting value, look to build a monopoly.',                                                         array['strategy','monopoly','contrarian']),
  ('marc-andreessen',   'Marc Andreessen',       'MA',  'Co-founder, Andreessen Horowitz',         'Andreessen Horowitz',   'Software is eating the world.',                                                                                                                                  array['investing','tech-trends','product-market-fit']),
  ('jason-lemkin',      'Jason Lemkin',         'JL',  'Founder, SaaStr',                         'SaaStr',                'Get to $1M ARR. Then hire. If you hire before, you''ll run out of money before you find product-market fit.',                                                    array['saas','b2b','fundraising']),
  ('arvid-kahl',        'Arvid Kahl',           'AK',  'Founder, FeedbackPanda',                  'FeedbackPanda',         'Embed yourself in your audience''s community before you build anything. Then build in public.',                                                                  array['bootstrapping','marketing','solo-founder']),
  ('nathan-barry',      'Nathan Barry',         'NB',  'Founder & CEO, Kit (ConvertKit)',          'Kit',                   'Teach everything you know. The more you give away, the more you get back.',                                                                                      array['saas','content','build-in-public']),
  ('tony-dinh',         'Tony Dinh',            'TD',  'Indie Hacker',                            'Xnapper / ScreenshotOne','Stop waiting for the perfect idea. Ship something small, charge for it, and iterate.',                                                                         array['indie-hacker','solo-founder','revenue']),
  ('lenny-rachitsky',   'Lenny Rachitsky',       'LR',  'Founder, Lenny''s Newsletter',            'Lenny''s Newsletter',   'The best growth comes from building something people genuinely want to share — not from growth hacks.',                                                          array['product','growth','pm']),
  ('april-dunford',     'April Dunford',         'AD',  'Founder, Ambient Strategy',               'Ambient Strategy',      'Positioning is the act of deliberately defining how you are the best at something that a defined market cares a lot about.',                                     array['positioning','marketing','messaging']),
  ('shane-parrish',     'Shane Parrish',         'SP',  'Founder, Farnam Street',                  'Farnam Street',         'Most people don''t actually think — they just rearrange their prejudices.',                                                                                       array['mental-models','decision-making','thinking']),
  ('tim-ferriss',       'Tim Ferriss',           'TF',  'Author & Investor',                       'Various',               'Focus on being productive instead of busy.',                                                                                                                     array['productivity','interviews','optimization']),
  ('jessica-livingston','Jessica Livingston',    'JLi', 'Co-founder, Y Combinator',                'Y Combinator',          'The most important quality in a founder is determination. Intelligence is fine, but tenacity is what counts.',                                                   array['yc','early-stage','founders']),
  ('michael-seibel',    'Michael Seibel',        'MS',  'Partner, Y Combinator',                   'Y Combinator',          'The number one cause of startup death is founders building something no one wants.',                                                                              array['yc','execution','startups']),
  ('andrew-wilkinson',  'Andrew Wilkinson',      'AW',  'Co-founder, Tiny',                        'Tiny',                  'Stop trying to build unicorns. Build a portfolio of boring cash-flow machines and compound quietly.',                                                             array['acquisitions','holding-company','operations']),
  ('brian-chesky',      'Brian Chesky',          'BC',  'Co-founder & CEO, Airbnb',                'Airbnb',                'Build something 100 people love, not something 1 million people kind of like.',                                                                                  array['design','hospitality','culture']),
  ('patrick-collison',  'Patrick Collison',      'PC',  'Co-founder & CEO, Stripe',                'Stripe',                'Move with urgency and focus. Slow is not safe — it is slow.',                                                                                                    array['payments','engineering','curiosity']),
  ('tobi-lutke',        'Tobi Lütke',            'TL',  'Co-founder & CEO, Shopify',               'Shopify',               'Entrepreneurship is a practice, not a destination.',                                                                                                              array['ecommerce','culture','scaling']),
  ('pieter-levels',     'Pieter Levels',         'PL',  'Founder, Nomad List & Remote OK',         'Nomad List',            'Make $1,000 first. Not $1 billion. Constraints breed creativity.',                                                                                               array['indie-hacker','bootstrapping','nomad']),
  ('dharmesh-shah',     'Dharmesh Shah',         'DS',  'Co-founder & CTO, HubSpot',               'HubSpot',               'Culture is to recruiting as product is to marketing. It compounds.',                                                                                             array['saas','inbound','culture'])
on conflict (slug) do update
  set name     = excluded.name,
      initials = excluded.initials,
      title    = excluded.title,
      company  = excluded.company,
      quote    = excluded.quote,
      tags     = excluded.tags;

-- Verify
select count(*) as total_founders from founders;
