"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useRouter } from "next/navigation";
import { ArrowUp, Check } from "lucide-react";
import { supabase } from "@/lib/supabase";

const WAITLIST_MODE = process.env.NEXT_PUBLIC_WAITLIST_MODE === "true";

const sampleResponse = {
  q: "How should I think about pricing?",
  a: "Start with what the outcome is worth, not what it costs you to build. Hormozi's framework: charge 10–20% of the economic value you deliver. Set prices higher than feels right — you can always come down, but raising prices on existing customers is painful. Most founders underprice by 3–5x in the first year.",
  sources: ["Hormozi", "PG"],
};

export default function Hero() {
  const [value, setValue] = useState("");
  const router = useRouter();

  // Waitlist state
  const [email, setEmail] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [duplicate, setDuplicate] = useState(false);
  const [count, setCount] = useState<number | null>(null);

  useEffect(() => {
    if (!WAITLIST_MODE) return;
    supabase
      .from("waitlist")
      .select("*", { count: "exact", head: true })
      .then(({ count: c }) => setCount(c ?? 0));
  }, []);

  const handleWaitlistSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = email.trim().toLowerCase();
    if (!trimmed || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) return;

    setSubmitting(true);
    setDuplicate(false);

    const { error } = await supabase
      .from("waitlist")
      .insert({ email: trimmed, source: "hero" });

    setSubmitting(false);

    if (error) {
      if (error.code === "23505") {
        setDuplicate(true);
      }
      return;
    }

    setSubmitted(true);
    setCount((c) => (c ?? 0) + 1);
  };

  const go = () => router.push("/app");
  const onKey = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); go(); }
  };

  return (
    <section id="waitlist-form" className="relative overflow-hidden" style={{ background: "#070B14" }}>

      {/* Subtle top glow */}
      <div className="pointer-events-none absolute top-0 left-1/2 -translate-x-1/2 w-[900px] h-[500px]"
        style={{ background: "radial-gradient(ellipse 70% 60% at 50% 0%, rgba(59,130,246,0.1) 0%, transparent 70%)" }} />

      {/* Above fold */}
      <div className="relative z-10 min-h-screen flex flex-col items-center justify-center w-full px-5">
        <div className="w-full max-w-2xl mx-auto flex flex-col items-center text-center pt-16">

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.05 }}
            className="text-[3.4rem] sm:text-[4.4rem] md:text-[5.4rem] lg:text-[6rem] font-bold tracking-[-0.04em] leading-[1.04] mb-6 text-white"
          >
            Think like the
            <br />
            founders who
            <br />
            built it.
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.15 }}
            className="text-[16px] md:text-[17px] text-white/45 max-w-[420px] mb-10 leading-relaxed"
          >
            Not generated by an AI that&apos;s never run a company — sourced from the people who have.
          </motion.p>

          {/* Glass prompt bar — always visible */}
          <motion.div
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="w-full mb-7"
          >
            <div className="p-px rounded-3xl" style={{ background: "linear-gradient(135deg, rgba(255,255,255,0.13) 0%, rgba(59,130,246,0.15) 100%)" }}>
              <div className="glass-shimmer relative rounded-[23px] backdrop-blur-xl overflow-hidden" style={{ background: "rgba(13,18,32,0.7)" }}>
                <div className="absolute inset-0 card-grid pointer-events-none opacity-100" />
                <div className="flex items-end gap-4 px-6 pt-5 pb-5">
                  <textarea
                    value={value}
                    onChange={e => setValue(e.target.value)}
                    onKeyDown={onKey}
                    placeholder="What decision are you working through?"
                    rows={3}
                    className="flex-1 bg-transparent text-[17px] text-white/90 placeholder:text-white/22 resize-none outline-none leading-relaxed"
                    style={{ minHeight: 88, maxHeight: 220 }}
                    onInput={e => {
                      const t = e.currentTarget;
                      t.style.height = "auto";
                      t.style.height = Math.min(t.scrollHeight, 220) + "px";
                    }}
                  />
                  <button
                    onClick={WAITLIST_MODE ? undefined : go}
                    disabled={WAITLIST_MODE}
                    className={`w-10 h-10 rounded-full flex items-center justify-center text-white transition-all duration-150 shrink-0 ${
                      WAITLIST_MODE
                        ? "bg-accent/30 cursor-not-allowed"
                        : "bg-accent hover:bg-blue-500"
                    }`}
                  >
                    <ArrowUp size={18} strokeWidth={2.5} />
                  </button>
                </div>
              </div>
            </div>
          </motion.div>

          {/* CTAs — conditional on WAITLIST_MODE */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.28 }}
            className="w-full"
          >
            {WAITLIST_MODE ? (
              <div className="flex flex-col items-center gap-3 w-full max-w-sm mx-auto">
                <AnimatePresence mode="wait">
                  {submitted ? (
                    <motion.div
                      key="success"
                      initial={{ opacity: 0, y: 4 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.3 }}
                      className="w-full flex items-center justify-center gap-2.5 px-5 py-3.5 rounded-2xl border border-white/[0.06] text-sm text-white/45"
                      style={{ background: "rgba(13,18,32,0.7)" }}
                    >
                      <span className="w-3.5 h-3.5 rounded-full bg-green-400/60 flex items-center justify-center shrink-0">
                        <Check size={9} strokeWidth={3} className="text-black" />
                      </span>
                      We&apos;ll be in touch.
                    </motion.div>
                  ) : duplicate ? (
                    <motion.div
                      key="duplicate"
                      initial={{ opacity: 0, y: 4 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.3 }}
                      className="w-full flex items-center justify-center px-5 py-3.5 rounded-2xl border border-white/[0.06] text-sm text-white/35"
                      style={{ background: "rgba(13,18,32,0.7)" }}
                    >
                      Already registered.
                    </motion.div>
                  ) : (
                    <motion.div key="form" className="w-full">
                      <div className="p-px rounded-2xl" style={{ background: "linear-gradient(135deg, rgba(255,255,255,0.09) 0%, rgba(59,130,246,0.1) 100%)" }}>
                        <form
                          onSubmit={handleWaitlistSubmit}
                          className="flex gap-2 p-1.5 rounded-[15px] backdrop-blur-xl"
                          style={{ background: "rgba(13,18,32,0.85)" }}
                        >
                          <input
                            type="email"
                            value={email}
                            onChange={e => setEmail(e.target.value)}
                            placeholder="your@email.com"
                            required
                            className="flex-1 min-w-0 px-4 py-2.5 bg-transparent text-[14px] text-white/80 placeholder:text-white/18 outline-none"
                          />
                          <button
                            type="submit"
                            disabled={submitting}
                            className="px-5 py-2.5 rounded-xl bg-accent hover:bg-blue-500 text-white text-[13px] font-medium tracking-tight transition-all duration-150 shrink-0 disabled:opacity-50"
                          >
                            {submitting ? (
                              <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin block" />
                            ) : (
                              "Notify me"
                            )}
                          </button>
                        </form>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                <p className="text-[11px] text-white/20">
                  {count !== null && count > 0
                    ? `${count.toLocaleString()} people signed up`
                    : "No spam."}
                </p>
              </div>
            ) : (
              <div className="flex items-center gap-4 justify-center">
                <a href="/app" className="px-6 py-2.5 rounded-full bg-accent hover:bg-blue-500 text-white text-sm font-medium transition-all duration-150">
                  Start free trial
                </a>
                <a href="#how-it-works" className="text-sm text-white/35 hover:text-white/60 transition-colors">
                  See how it works →
                </a>
              </div>
            )}
          </motion.div>
        </div>
      </div>

      {/* Below fold — glass sample response */}
      <div className="relative z-10 w-full max-w-2xl mx-auto px-5 pb-28">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <div className="p-px rounded-3xl" style={{ background: "linear-gradient(180deg, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0.03) 100%)" }}>
            <div className="glass-shimmer relative rounded-[23px] overflow-hidden backdrop-blur-xl" style={{ background: "rgba(12,17,24,0.65)" }}>
              <div className="absolute inset-0 card-grid pointer-events-none" />
              <div className="px-5 pt-5 pb-4 flex justify-end">
                <div className="max-w-[75%] backdrop-blur-sm bg-white/[0.06] border border-white/[0.08] rounded-2xl rounded-br-sm px-4 py-2.5 text-sm text-white/65">
                  {sampleResponse.q}
                </div>
              </div>
              <div className="h-px mx-5" style={{ background: "rgba(255,255,255,0.04)" }} />
              <div className="px-5 py-5 flex gap-3">
                <div className="w-7 h-7 rounded-full flex items-center justify-center shrink-0 mt-0.5 ring-glow-accent"
                  style={{ background: "linear-gradient(135deg, rgba(59,130,246,0.18), rgba(13,18,32,0.8))" }}>
                  <span className="text-accent/60 text-[8px] font-bold">BL</span>
                </div>
                <div className="flex-1">
                  <p className="text-[13px] text-white/60 leading-relaxed mb-3">{sampleResponse.a}</p>
                  <div className="flex gap-2">
                    {sampleResponse.sources.map(s => (
                      <span key={s} className="px-3 py-1 rounded-full border border-accent/15 text-[11px] text-accent/40">
                        {s}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
